web:
    image: nginx:latest
    ports:
        - "8080:80"
        - "443:443"
    volumes:
        - ./www:/var/www/html
        - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7.4-fpm
    ports:
        - "9080:9000"
    volumes:
        - ./www:/var/www/html
        - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
        - redis
redis:
    image: redis:latest
    ports:
        - "6379:6379"